server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: 49thisef
    key-store-type: PKCS12
    key-alias: service-cert
app:
  output-dir: /app/output